{% set name = "smqtk-dataprovider" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_dataprovider-{{ version }}.tar.gz
  sha256: 66ccd5d6b0d5e8fe77f714e597a0b7f8eb288089b9b7251a27f1c76869b530aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.23.5
    - requests >=2.28.1
    - smqtk-core >=0.19

test:
  imports:
    - smqtk_dataprovider
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/SMQTK-Dataprovider
  summary: SMQTK Data provision abstractions and implementations
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
